### ISSUE TITLE
Expose Zarr hierarchy Node private attrs 

### ISSUE THREAD

**Issue by lorenzocerrone** [LDeakin/zarrs#12]
Hi! 

Thanks for this fantastic library :) 

I would like to ask if it would be possible to implement methods that allow access to the `Node.metadata` and the `Node.children.` (unless it's already possible, I am a beginner with rust and this crate)

If this feature interests you, I can try to draft a PR myself.  Just for some context, I am writing an interactive Zarr explorer to learn rust, and it would be amazing to access those two private fields.

**Comment by LDeakin** [comment]
Of course! feel free to open a PR.
