### ISSUE TITLE
How to read/write string Arrays?

### ISSUE THREAD

**Issue by kaizhang** [LDeakin/zarrs#21]
Are there any examples to demonstrate how to read/write string Arrays?

**Comment by LDeakin** [comment]
`zarrs` does not currently support strings or variable length data types. I am waiting for the [draft Zarr V3 ZEP for strings](https://github.com/zarr-developers/zeps/pull/47) to progress.

**Comment by LDeakin** [comment]
Support for strings has been added, there is an example here: https://github.com/LDeakin/zarrs/blob/main/examples/array_write_read_string.rs

Variable length data types/codecs are experimental and will not be compatible with other implementations likely for some time. Track standardisation progress here: https://github.com/zarr-developers/zeps/pull/47
