### ISSUE TITLE
Support for ReadableWritableStorage in AsyncToSyncStorageAdapter

### ISSUE THREAD

**Issue by dustinlagoy** [LDeakin/zarrs#54]
Hey there, thanks for the awesome library! I've been using it to prototype a zarr writer for a project and was trying out the `AsyncTosyncStorageAdapter` which seems to work well, but is missing support for the `ReadableWritableStorage` and `ReadableWritableListableStorage` traits. Is there any specific reason these are not implemented?

I made a new type and added (in addition to all the forwarding boilerplate):

```rust
impl<TStorage: ?Sized + AsyncReadableWritableStorageTraits, TBlockOn: AsyncToSyncBlockOn>
    ReadableWritableStorageTraits for MyNewAdapter<TStorage, TBlockOn>
{
}
```

which seems to work fine. If there isn't some fundamental reason you avoided implementing these I'd be happy to open a quick pull request.

**Comment by LDeakin** [comment]
> Hey there, thanks for the awesome library

Much appreciated :)

Looks like I missed implementing this in `storage_sync.rs`:
```
impl<T> ReadableWritableStorageTraits for T where T: ReadableStorageTraits + WritableStorageTraits {}
```
`ReadableWritableListableStorage` comes for free from that as well.

Would you like to contribute the fix? Some conflicting implementations would need to be removed afterwards in the various stores.

**Comment by dustinlagoy** [comment]
Sure! I'll try to work on it sometime in the next few days.
